//
//  NSDictionary+PropertyCode.h
//  JCAutoGeneratedAttributes
//
//  Created by 陈鹏 on 16/5/3.
//  Copyright © 2016年 JackeyChen. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface NSDictionary (PropertyCode)

- (void)autoCreatePropetyCode;

@end
