//
//  ViewController.m
//  JCAutoGeneratedAttributes
//
//  Created by 陈鹏 on 16/5/3.
//  Copyright © 2016年 JackeyChen. All rights reserved.
//

#import "ViewController.h"
#import "NSDictionary+PropertyCode.h"

@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
}

- (void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event{
    
    // 解析Plist
    // 获取文件全路径
    NSString *fileName = [[NSBundle mainBundle] pathForResource:@"apps.plist" ofType:nil];
    // 获取字典
    NSDictionary *dict = [NSDictionary dictionaryWithContentsOfFile:fileName];
    
    // 自动生成属性代码
    [dict autoCreatePropetyCode];
}

@end
